spring.application.name=crudSpringBootDemo
spring.datasource.url=jdbc:mysql://localhost:3306/stud_crud_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true
#spring.jpa.properties.dialect=org.hibernate.dialect.MySQL5Dialect